
FROM openjdk:21-oracle
WORKDIR /app

COPY ./BodyManager-0.0.1-SNAPSHOT.war /app/BodyManager-0.0.1-SNAPSHOT.war
EXPOSE 8080
ENTRYPOINT [  "java",                                     \ 
    "-jar",                                     \
    "/app/BodyManager-0.0.1-SNAPSHOT.war"                        \
    ]






